package com.example.android.demo.GreenDao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.example.android.demo.Db.Student;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT".
*/
public class StudentDao extends AbstractDao<Student, Long> {

    public static final String TABLENAME = "STUDENT";

    /**
     * Properties of entity Student.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StuNo = new Property(1, int.class, "stuNo", false, "stu_no");
        public final static Property StuName = new Property(2, String.class, "stuName", false, "stu_name");
        public final static Property TeacherId = new Property(3, Long.class, "teacherId", false, "teacher_id");
        public final static Property StuAge = new Property(4, String.class, "stuAge", false, "stu_age");
        public final static Property StuPrice = new Property(5, String.class, "stuPrice", false, "stu_price");
    }

    private Query<Student> teacher_StudentsQuery;

    public StudentDao(DaoConfig config) {
        super(config);
    }
    
    public StudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"stu_no\" INTEGER NOT NULL ," + // 1: stuNo
                "\"stu_name\" TEXT NOT NULL ," + // 2: stuName
                "\"teacher_id\" INTEGER," + // 3: teacherId
                "\"stu_age\" TEXT," + // 4: stuAge
                "\"stu_price\" TEXT);"); // 5: stuPrice
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_STUDENT_stu_no ON \"STUDENT\"" +
                " (\"stu_no\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Student entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStuNo());
        stmt.bindString(3, entity.getStuName());
 
        Long teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindLong(4, teacherId);
        }
 
        String stuAge = entity.getStuAge();
        if (stuAge != null) {
            stmt.bindString(5, stuAge);
        }
 
        String stuPrice = entity.getStuPrice();
        if (stuPrice != null) {
            stmt.bindString(6, stuPrice);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Student entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStuNo());
        stmt.bindString(3, entity.getStuName());
 
        Long teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindLong(4, teacherId);
        }
 
        String stuAge = entity.getStuAge();
        if (stuAge != null) {
            stmt.bindString(5, stuAge);
        }
 
        String stuPrice = entity.getStuPrice();
        if (stuPrice != null) {
            stmt.bindString(6, stuPrice);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Student readEntity(Cursor cursor, int offset) {
        Student entity = new Student( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // stuNo
            cursor.getString(offset + 2), // stuName
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // teacherId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // stuAge
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // stuPrice
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Student entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStuNo(cursor.getInt(offset + 1));
        entity.setStuName(cursor.getString(offset + 2));
        entity.setTeacherId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setStuAge(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStuPrice(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Student entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Student entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Student entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "students" to-many relationship of Teacher. */
    public List<Student> _queryTeacher_Students(Long teacherId) {
        synchronized (this) {
            if (teacher_StudentsQuery == null) {
                QueryBuilder<Student> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TeacherId.eq(null));
                teacher_StudentsQuery = queryBuilder.build();
            }
        }
        Query<Student> query = teacher_StudentsQuery.forCurrentThread();
        query.setParameter(0, teacherId);
        return query.list();
    }

}
